@startuml
package entities {
    abstract class Entity {
        - Vec2 pos
        - Vec2 vel
        - Vec2 acc

        + update()
        + render()
    }

    interface Edible {
        + int getFoodValue()
        + void isEatenBy(HostileCreature)
    } 
}

package entities.bodysegments {
    abstract BodySegment extends entities.Entity {
        ~ int maxSaturation
        ~ int saturation
        + int saturate(foodValue)
        + void desaturate()

    } 
}

package entities.hostile {
    abstract class HostileCreature {
        + Mouth getMouth()
        + Edible checkCollisionsWithMouth(Mouth)
        
        + void eat(Edible)
        
        + boolean isAlive()
        + void getRemains()
    }
}

package entities.peaceful {

}

package util {
    class Ring {
        static Shape create ()
    }
    class Vec2 {
        double x
        double y
    }
}


class Game {
}

class Level {

}


@enduml